apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t2i54vfeo-python
  janus-idp.io/tekton: t2i54vfeo-python
  backstage.io/kubernetes-id: t2i54vfeo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t2i54vfeo-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
