apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t2i54vfeo-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:667297abc4feeaaaf55e23e9ae6fcb5fd401009d@sha256:551f0fe9b95324b172122dd430ea14f3f3023420832be96906b1857b4b72809a
          name: container-image
